app/coffeeshop/urls.py
from django.urls import path

from . import views

app_name = 'coffeeshop'

urlpatterns = [
    path('starbucks/', views.starbucks_total_list, name='starbucks'),
    path('starbucks/<str:category>/', views.starbucks_category_coffee, name='starbucks-category'),
    path('twosomeplace/', views.twosome_total_list, name='twosome'),
    path('twosomeplace/<str:category>/', views.twosome_category_coffee, name='twosome-category'),
    path('search/', views.coffee_search_list, name='calorie-search')
]

app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main_page, name='main-page'),
    path('coffeeshop/', include('coffeeshop.urls')),
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

app/coffeeshop/models.py
from django.db import models


def coffee_path(instance, filename):
    starbucks = 'starbucks'
    twosome = 'ATwosomePlace'

    if instance.coffee.coffeeshop_list == 'STARBUCKS':
        starbucks_path = f'{starbucks}/{instance.coffee.name}.jpg'
        return starbucks_path
    elif instance.coffee.coffeeshop_list == 'ATWOSOMEPLACE':
        twosome_path = f'{twosome}/{instance.coffee.name}.jpg'
        return twosome_path


class CoffeeCategory(models.Model):
    name = models.CharField('카테고리', max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '카테고리'
        verbose_name_plural = f'{verbose_name} 목록'


class Coffee(models.Model):
    COFFEESHOP_LIST = (
        ('STARBUCKS', '스타벅스'),
        ('ATWOSOMEPLACE', '투썸플레이스'),
    )
    category = models.ForeignKey(
        CoffeeCategory,
        on_delete=models.SET_NULL,
        verbose_name='카테고리',
        null=True,
    )
    coffeeshop_list = models.CharField(max_length=20, choices=COFFEESHOP_LIST)
    name = models.CharField('커피', max_length=100)
    coffee_info = models.TextField('커피소개', blank=True,)
    coffee_size = models.CharField('커피사이즈', max_length=80, blank=True,)
    calorie = models.IntegerField('칼로리', blank=True, null=True)
    calorie_large = models.IntegerField('라지사이즈칼로리', blank=True, null=True)
    saturated_fat = models.CharField('포화지방', max_length=80, blank=True,)
    protein = models.CharField('단백질', max_length=80, blank=True,)
    sodium = models.CharField('나트룸', max_length=80, blank=True,)
    sugars = models.CharField('당류', max_length=80, blank=True,)
    caffeine = models.CharField('카페인', max_length=80, blank=True,)
    created_at = models.DateTimeField('등록일', auto_now_add=True)

    def __str__(self):
        return '{category}::{name}'.format(
            category=self.category,
            name=self.name,
        )

    class Meta:
        verbose_name = '커피'
        verbose_name_plural = f'{verbose_name} 목록'


class CoffeeImage(models.Model):
    location = models.ImageField('커피이미지', upload_to=coffee_path, blank=True)
    coffee = models.ForeignKey(
        Coffee,
        on_delete=models.CASCADE,
        verbose_name='커피'
    )
    created_at = models.DateTimeField('등록일', auto_now_add=True)

    def __str__(self):
        return '{coffee}'.format(
            coffee=self.coffee,
        )

    class Meta:
        verbose_name = '커피이미지'
        verbose_name_plural = f'{verbose_name} 목록'

app/coffeeshop/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404

from .models import Coffee, CoffeeCategory, CoffeeImage


def starbucks_total_list(request):
    starbucks = Coffee.objects.filter(coffeeshop_list='STARBUCKS')

    # pagination (전체보기 적용)
    paginator = Paginator(starbucks, 6)
    page = request.GET.get('page')

    try:
        starbucks = paginator.page(page)
    except PageNotAnInteger:
        starbucks = paginator.page(1)
    except EmptyPage:
        starbucks = paginator.page(paginator.num_pages)

    # url의 쿼리스트링을 가져옴. 없는 경우 None을 리턴
    calorie = request.GET.get('calorie', '')

    if calorie == 'high':
        starbucks = Coffee.objects.filter(coffeeshop_list='STARBUCKS').order_by('-calorie')
        return render(request, 'coffeeshop/starbucks_total_list.html', {'starbucks': starbucks})

    elif calorie == 'low':
        starbucks = Coffee.objects.filter(coffeeshop_list='STARBUCKS').order_by('calorie')
        return render(request, 'coffeeshop/starbucks_total_list.html', {'starbucks': starbucks})

    context = {
        'starbucks': starbucks,
    }
    return render(request, 'coffeeshop/starbucks_total_list.html', context)


def starbucks_category_coffee(request, category):
    coffee = Coffee.objects.filter(coffeeshop_list='STARBUCKS').filter(category__name__contains=category)
    # url의 쿼리스트링을 가져옴. 없는 경우 None을 리턴
    calorie = request.GET.get('calorie', 'None')

    if calorie == 'high':
        coffee = Coffee.objects.filter(category__name__contains=category).order_by('-calorie')
        return render(request, 'coffeeshop/starbucks_category_coffee.html', {'coffee': coffee})

    elif calorie == 'low':
        coffee = Coffee.objects.filter(category__name__contains=category).order_by('calorie')
        return render(request, 'coffeeshop/starbucks_category_coffee.html', {'coffee': coffee})

    context = {
        'coffee': coffee,
    }
    return render(request, 'coffeeshop/starbucks_category_coffee.html', context)


# 투썸 커피 전체보기
def twosome_total_list(request):
    twosome = Coffee.objects.filter(coffeeshop_list='ATWOSOMEPLACE')

    # pagination (전체보기 적용)
    paginator = Paginator(twosome, 6)
    page = request.GET.get('page')

    try:
        twosome = paginator.page(page)
    except PageNotAnInteger:
        twosome = paginator.page(1)
    except EmptyPage:
        twosome = paginator.page(paginator.num_pages)

    # url의 쿼리스트링을 가져옴. 없는 경우 None을 리턴
    calorie = request.GET.get('calorie', '')

    if calorie == 'high':
        twosome = Coffee.objects.filter(coffeeshop_list='ATWOSOMEPLACE').order_by('-calorie')
        return render(request, 'coffeeshop/twosome_total_list.html', {'twosome': twosome})

    elif calorie == 'low':
        twosome = Coffee.objects.filter(coffeeshop_list='ATWOSOMEPLACE').order_by('calorie')
        return render(request, 'coffeeshop/twosome_total_list.html', {'twosome': twosome})

    context = {
        'twosome': twosome,
    }
    return render(request, 'coffeeshop/twosome_total_list.html', context)


# 투썸 커피 카테고리
def twosome_category_coffee(request, category):
    coffee = Coffee.objects.filter(coffeeshop_list='ATWOSOMEPLACE').filter(category__name__contains=category)

    calorie = request.GET.get('calorie', 'None')

    if calorie == 'high':
        coffee = Coffee.objects.filter(category__name__contains=category).order_by('-calorie')
        return render(request, 'coffeeshop/twosome_category_coffee.html', {'coffee': coffee})

    elif calorie == 'low':
        coffee = Coffee.objects.filter(category__name__contains=category).order_by('calorie')
        return render(request, 'coffeeshop/twosome_category_coffee.html', {'coffee': coffee})

    context = {
        'coffee': coffee,
    }
    return render(request, 'coffeeshop/twosome_category_coffee.html', context)


# 커피 검색기능
def coffee_search_list(request):
    coffee_list = Coffee.objects.all()

    # GET request의 인자중에 keyword 값이 있으면 가져오고 없으면 빈문자열
    keyword = request.GET.get('keyword', '')

    if keyword:
        coffee_list = coffee_list.filter(name__icontains=keyword)
        # 검색어를 저장하기 위해서 non_keyword 라는 변수 생성
        # non_keyword 는 해당 검색(keyword)에 없는 경우
        # non_keyword를 통해 해당 검색어를 리턴해주기 위해 생성
        non_keyword = request.GET['keyword']

        if not coffee_list:
            context = {
                'non_keyword': non_keyword,
            }
            return render(request, 'coffeeshop/coffee_search.html', context)
    context = {
        'coffee_list': coffee_list,
        'keyword': keyword,
    }
    return render(request, 'coffeeshop/coffee_search.html', context)

app/config/views.py
from django.shortcuts import render


def main_page(request):
    return render(request, 'coffeeshop/coffeecalorie_main_page.html')

app/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CoffeeCalories</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <style>
    * {
     margin: 0;
     padding: 0;
    }
    .container {
      width: 100%;
      padding-right: 15px;
      padding-left: 15px;
      margin-right: auto;
      margin-left: auto;
    }
    ul > li {
     list-style: none;
     padding: 0;
     margin: 0;
    }
    /* 롯데마트 드림체 */
    @font-face {
      font-family: 'LotteMartDream';
      src: url('//cdn.jsdelivr.net/korean-webfonts/1/corps/lottemart/LotteMartDream/LotteMartDreamBold.woff2') format('woff2'), url('//cdn.jsdelivr.net/korean-webfonts/1/corps/lottemart/LotteMartDream/LotteMartDreamBold.woff') format('woff');
    }
    .lottemartdream  {
     font-family: 'LotteMartDream', sans-serif;
    }

    .normal {
     font-style: normal;
    }

    .w900 {
     font-weight: 900;
     font-size: 36px;
    }
    .search_coffee {
     font-weight: 900;
     font-size: 20px;
    }
    .coffee_sub_title {
     font-weight: 900;
     font-size: 20px;
    }
    .w100 {
     font-weight: 100;
     font-size: 18px;
    }

    /* 스포카 한스 폰트  */
    @import url(//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css);
    @import url(//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-jp.css);
    .spoqahansans {
      font-family: 'Spoqa Han Sans', 'Spoqa Han Sans JP', 'Sans-serif';
    }

    .padding {
      padding: 20px 20px 20px 0px;
    }


    img {
      max-width: 100%; /* 이미지의 최대사이즈 */
      width: 100%;
      vertical-align: middle;
    }
    .slideimage {
      width: 100%;
      height: 500px;
      max-height: 100%;
    }
    .carousel-inner{
      width: 100%;
      height: 100%;
      overflow: hidden;
    }
    footer > ul > li {
      list-style: none;
      text-align: right;
    }
    .coffee_info {
      font-size: 12px;
      font-weight: 100;
    }
    .coffee_info  li.card-text {
      padding-right: 5px;
      color: #3e3e3e;
    }
    .coffee_name {
      font-size: 18px;
      font-weight: 600;
    }
    .coffee_size {
     font-size: 14px;
     font-weight: 200;
    }
    .coffee_details {
     font-size: 16px;
    }
    .left {
     float: left;
     list-style: none;
    }
    div.card-body > ul > li {
     list-style: none;
     padding: 0;
     float: left;
    }
    nav > .pagination li {
      float: left;
    }

    # 검색창 글씨 및 placeholder 색상
   .search_font {

    }
    .search_font::placeholder {
      color: #8b8c8e;
      font-weight: 100;
      font-size: 90%;
    }

    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-12">
            <header class="navbar navbar-expand-lg navbar-light lottemartdream" style="background-color:#fff;">
                <!-- Brand -->
                <a href="{% url 'main-page' %}" class="navbar-brand normal w900 padding">Coffeecalorie</a>

                <!-- Button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                  <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a href="{% url 'coffeeshop:starbucks' %}" class="nav-link w300 dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">스타벅스</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a href="{% url 'coffeeshop:starbucks' %}" class="dropdown-item">전체보기</a>
                            <a href="{% url 'coffeeshop:starbucks-category' category='콜드 브루 커피' %}" class="dropdown-item">콜드 브루 커피</a>
                            <a href="{% url 'coffeeshop:starbucks-category' category='브루드 커피' %}" class="dropdown-item">브루드 커피</a>
                            <a href="{% url 'coffeeshop:starbucks-category' category='에스프레소' %}" class="dropdown-item">에스프레소</a>
                            <a href="{% url 'coffeeshop:starbucks-category' category='프라푸치노' %}" class="dropdown-item">프라푸치노</a>
                            <a href="{% url 'coffeeshop:starbucks-category' category='블렌디드' %}" class="dropdown-item">블렌디드</a>
                            <a href="{% url 'coffeeshop:starbucks-category' category='스타벅스 피지오' %}" class="dropdown-item">스타벅스 피지오</a>
                            <a href="{% url 'coffeeshop:starbucks-category' category='티(티바나)' %}" class="dropdown-item">티(티바나)</a>
                            <a href="{% url 'coffeeshop:starbucks-category' category='기타 제조 음료' %}" class="dropdown-item">기타 제조 음료</a>
                            <a href="{% url 'coffeeshop:starbucks-category' category='스타벅스 주스(병음료)' %}" class="dropdown-item">스타벅스 주스(병음료)</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a href="{% url 'coffeeshop:twosome' %}" class="nav-link w300 dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">투썸플레이스</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a href="{% url 'coffeeshop:twosome' %}" class="dropdown-item">전체보기</a>
                            <a href="{% url 'coffeeshop:twosome-category' category='에스프레소' %}" class="dropdown-item">에스프레소</a>
                            <a href="{% url 'coffeeshop:twosome-category' category='블렌디드' %}" class="dropdown-item">블렌디드</a>
                            <a href="{% url 'coffeeshop:twosome-category' category='티(TWG)' %}" class="dropdown-item">티(TWG)</a>
                            <a href="{% url 'coffeeshop:twosome-category' category='기타' %}" class="dropdown-item">기타</a>
                        </div>
                    </li>
                  </ul>
                  <form action="{% url 'coffeeshop:calorie-search' %}" class="form-inline my-2 my-lg-0" method="get">
                      <input type="text" class="form-control mr-sm-2 search_font" placeholder="커피명을 검색해보세요" aria-label="Search" name="keyword">
                      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                  </form>
                </div>
            </header>
            {% block slider %}

            {% endblock %}

            {% block content %}

            {% endblock %}
            </div>
        </div>
 </div>
<script type="text/javascript">
// get url query string

var getUrlParameter = function getUrlParameter(sParam) {
    var sPageURL = decodeURIComponent(window.location.search.substring(1)),
        sURLVariables = sPageURL.split('&'),
        sParameterName,
        i;

    for (i = 0; i < sURLVariables.length; i++) {
        sParameterName = sURLVariables[i].split('=');

        if (sParameterName[0] === sParam) {
            return sParameterName[1] === undefined ? true : sParameterName[1];
        }
    }
};

// 정렬방식 셀렉트 박스 유지
$(document).ready(function(){
  var calorie = getUrlParameter('calorie');
  if(calorie == 'high'){
    $('.calorie-high').prop('selected', 'selected')
  }else if(calorie == 'low'){
    $('.calorie-low').prop('selected', 'selected')
  }
});
</script>
</body>
</html>

app/templates/coffeeshop/coffees_total_list.html
{% extends 'base.html' %}

{% block content %}

<div style="padding: 15px 0px 20px 20px;">
    <h4 class="lottemartdream normal coffee_sub_title">Starbucks Coffee Calories</h4>
</div>

<!-- select box -->
<div class="form-group lottemartdream">
    <select id="sell" class="form-control" onchange="location=this.value;" style="max-width:50%; max-height:30%;">
        <option selected value="{% url 'coffeeshop:starbucks' %}">옵션 선택 하기</option>
        <option value="?calorie=high" class="calorie-high">칼로리 높은순으로</option>
        <option value="?calorie=low" class="calorie-low">칼로리 낮은순으로</option>
    </select>
</div>

<!--Card deck -->
<div class="card-deck lottemartdream">
    {% for detail in details %}
            {% for image in detail.coffeeimage_set.all %}
                <div class="card mb-3 tab-pane fade show active" id="allcoffee" role="tabpanel" aria-labelledby="all_coffee" style="min-width: 16rem;">
                    <img src="{{ image.location.url }}" alt="" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title w400 coffee_name" style="margin:0;">{{ detail.name }}</h5>
                        <span class="coffee_size" style="padding-top:0.1%; color:#4c4c4c;">{{ detail.coffee_size }}</span>
                        <span><p class="card-text coffee_info" style="padding-top:1.5%; color:#8a8a8a;">{{ detail.coffee_info }}</p></span>
                        <ul class="coffee_info" style="padding-top:10px;">
                            <li class="card-text">칼로리(kcal): {{ detail.calorie }}</li>
                            <li class="card-text">포화지방(g): {{ detail.saturated_fat }}</li>
                            <li class="card-text">단백질(g): {{ detail.protein }}</li>
                            <li class="card-text left">나트륨(mg): {{ detail.sodium }}</li>
                            <li class="card-text left">당류(g): {{ detail.sugars }}</li>
                            <li class="card-text left">카페인(g): {{ detail.caffeine }}</li>
                        </ul>
                    </div>
                </div>
            {% endfor %}
    {% endfor %}
</div>

<nav style="text-align: center;">
    <ul class="pagination" style="display:inline-block;">
        {% if details.has_previous %}
        <li class="page-item">
            <a href="?page={{ details.previous_page_number }}&calorie=" class="page-link">이전</a>
        </li>
        {% endif %}

        <li class="page-item active">
            <span href="#" class="page-link">
                {{ details.number }} of {{details.paginator.num_pages }}
            </span>
        </li>

        {% if details.has_next %}
        <li class="page-item">
            <a href="?page={{ details.next_page_number }}" class="page-link">다음</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endblock %}

app/templates/coffeeshop/crawling_result_email.html
1. 신상(업데이트) 커피

{% for key, value in dict_log.updated_coffee.items %}

    커피체인점 : {{ key }}

    업데이트 된 커피 수 : {{ value.num }}

    커피명 : {% for coffee in value.list %}
                {{ coffee }}
           {% endfor %}

{% endfor %}

2. 커피 총 수량

{% for key, value in dict_log.total_coffee.items %}

    커피체인점 : {{ key }}

    커피 수 : {{ value.num }}

    커피명 : {% for coffee in value.list %}
                {{ coffee }}
           {% endfor %}

{% endfor %}

app/templates/coffeeshop/starbucks_total_list.html
{% extends 'base.html' %}

{% block content %}

<div style="padding: 15px 0px 20px 20px;">
    <h4 class="lottemartdream normal coffee_sub_title col-12 mx-auto">Starbucks Coffee Calories</h4>
</div>

<!-- select box -->
<div class="form-group lottemartdream col-12 mx-auto">
    <select id="sell" class="form-control" onchange="location=this.value;" style="width:200px; max-height:30%;">
        <option selected value="{% url 'coffeeshop:starbucks' %}">옵션 선택 하기</option>
        <option value="?calorie=high" class="calorie-high">칼로리 높은순으로</option>
        <option value="?calorie=low" class="calorie-low">칼로리 낮은순으로</option>
    </select>
</div>

<!--Card deck -->
<div class="card-deck lottemartdream col-12 mx-auto">
    {% for detail in starbucks %}
            {% for image in detail.coffeeimage_set.all %}
                <div class="card mb-3 tab-pane fade show active" id="allcoffee" role="tabpanel" aria-labelledby="all_coffee" style="min-width: 20rem; max-width: 20rem;">
                    <img src="{{ image.location.url }}" alt="" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title w400 coffee_name" style="margin:0;">{{ detail.name }}</h5>
                        <span class="coffee_size" style="padding-top:0.1%; color:#4c4c4c;">{{ detail.coffee_size }}</span>
                        <span><p class="card-text coffee_info" style="padding-top:1.5%; color:#8a8a8a;">{{ detail.coffee_info }}</p></span>
                        <ul class="coffee_info" style="padding-top:10px;">
                            <li class="card-text">칼로리(kcal): {{ detail.calorie }}</li>
                            <li class="card-text">포화지방(g): {{ detail.saturated_fat }}</li>
                            <li class="card-text">단백질(g): {{ detail.protein }}</li>
                            <li class="card-text left">나트륨(mg): {{ detail.sodium }}</li>
                            <li class="card-text left">당류(g): {{ detail.sugars }}</li>
                            <li class="card-text left">카페인(g): {{ detail.caffeine }}</li>
                        </ul>
                    </div>
                </div>
            {% endfor %}
    {% endfor %}
</div>
<nav style="text-align: center;">
    <ul class="pagination" style="display:inline-block;">
        {% if starbucks.has_previous %}
        <li class="page-item">
            <a href="?page={{ starbucks.previous_page_number }}&calorie=" class="page-link">이전</a>
        </li>
        {% endif %}

        <li class="page-item active">
            <span href="#" class="page-link">
                {{ starbucks.number }} of {{ starbucks.paginator.num_pages }}
            </span>
        </li>

        {% if starbucks.has_next %}
        <li class="page-item">
            <a href="?page={{ starbucks.next_page_number }}" class="page-link">다음</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endblock %}

app/templates/coffeeshop/twosome_total_list.html
{% extends 'base.html' %}

{% block content %}

<div style="padding: 15px 0px 20px 20px;">
    <h4 class="lottemartdream normal coffee_sub_title col-12 mx-auto">A Twosome Place Coffee Calories</h4>
</div>

<!-- select box -->
<div class="form-group lottemartdream col-12 mx-auto">
    <select id="sell" class="form-control" onchange="location=this.value;" style="width:200px; max-height:30%;">
        <option selected value="{% url 'coffeeshop:twosome' %}">옵션 선택 하기</option>
        <option value="?calorie=high" class="calorie-high">칼로리 높은순으로</option>
        <option value="?calorie=low" class="calorie-low">칼로리 낮은순으로</option>
    </select>
</div>

<!--Card deck -->
<div class="card-deck lottemartdream col-12 mx-auto">
    {% for detail in twosome %}
            {% for image in detail.coffeeimage_set.all %}
                <div class="card mb-3 tab-pane fade show active" id="allcoffee" role="tabpanel" aria-labelledby="all_coffee" style="min-width: 20rem; max-width: 20rem;">
                    <img src="{{ image.location.url }}" alt="" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title w400 coffee_name" style="margin:0;">{{ detail.name }}</h5>
                        <span class="coffee_size" style="padding-top:0.1%; color:#4c4c4c;">{{ detail.coffee_size }}</span>
                        <span><p class="card-text coffee_info" style="padding-top:1.5%; color:#8a8a8a;">{{ detail.coffee_info }}</p></span>
                        <ul class="coffee_info" style="padding-top:10px;">
                            <li class="card-text">칼로리_레귤러(kcal): {{ detail.calorie }}</li>
                            {% if detail.calorie_large is not None %}
                            <li class="card-text">칼로리_라지(kcal): {{ detail.calorie_large }}</li>
                            {% endif %}
                            <li class="card-text">포화지방(g/%): {{ detail.saturated_fat }}</li>
                            <li class="card-text">단백질(g/%): {{ detail.protein }}</li>
                            <li class="card-text left">나트륨(mg/%): {{ detail.sodium }}</li>
                            <li class="card-text left">당류(g): {{ detail.sugars }}</li>
                        </ul>
                    </div>
                </div>
            {% endfor %}
    {% endfor %}
</div>

<nav style="text-align: center;">
    <ul class="pagination" style="display:inline-block;">
        {% if twosome.has_previous %}
        <li class="page-item">
            <a href="?page={{ twosome.previous_page_number }}&calorie=" class="page-link">이전</a>
        </li>
        {% endif %}

        <li class="page-item active">
            <span href="#" class="page-link">
                {{ twosome.number }} of {{ twosome.paginator.num_pages }}
            </span>
        </li>

        {% if twosome.has_next %}
        <li class="page-item">
            <a href="?page={{ twosome.next_page_number }}" class="page-link">다음</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endblock %}